### ISSUE TITLE
Tool verification

### ISSUE THREAD

**Issue by barnettwilliam** [mdenet/platformtools#54]
To ensure quality, reliability, and assist future development tool services should have continuous test and integration capability with adequate coverage of key features.

- [ ] Setup code coverage and reporting

- [ ] Xtext tool

    - [ ] Create unit tests

    - [ ] Create API tests and document

**Comment by barnettwilliam** [comment]
Linting and code coverage for Xtext editor server added by PRs #63 and #64.

**Comment by szschaler** [comment]
Partly contributes to https://github.com/mdenet/educationplatform/issues/216
